### ISSUE TITLE
Inconsistent Weights for Liquidity Bootstrapping Pools

### ISSUE THREAD

**Issue by nlordell** [balancer-labs/balancer-subgraph-v2#173]
I noticed what looks like inconsistent weights for a `LiquidityBootstrapping` pool (`0x053f3c35d557A76E9cB6C13a4842d9cFCDdAc833` - there could be more, I did not check).

Specifically, when querying the subgraph is produces weights of `~0.97774` and `~0.02226`:
```
$ curl -s \
  'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2' \
  -X POST \
  -H 'Content-Type: application/json' \
  --data-raw '{"query":"{ pools(where: { id: \"0x053f3c35d557a76e9cb6c13a4842d9cfcddac8330002000000000000000000cd\" }) { tokens { weight } }}","variables":null}' \
  | jq -r '.data.pools[0].tokens[] | .weight'
0.022267422838857067
0.977747836185951854
```

(Note that the total weights are `1.000015259024808921` and not `1.0` as I would expect.)

However, when quering the contract with an `eth_call`, I get completely different weights. Some sample code with Ethers.js:
```js
const provider = ethers.getDefaultProvider("mainnet");
const pool = new ethers.Contract(
  "0x053f3c35d557A76E9cB6C13a4842d9cFCDdAc833",
  ["function getNormalizedWeights() view returns (uint256[])"],
  provider,
);

const weights = await pool.getNormalizedWeights();
for (const weight of weights) {
  console.log(ethers.utils.formatUnits(weight, 18));
}
```

The weights I get are:
```
0.010009918364232853
0.990005340657663844
```

(Note that these also don't sum up to a total of `1.0` as I would expect but instead `1.000015259021896697`.)

**Comment by EndymionJkb** [comment]
The weights are stored in a compressed format, so that the entire pool state fits into one slot. That compression and decompression is why they are not exactly 1.0.

In the subgraph (which of course needs to be triggered by an event in order to do anything), the weights are updated after every swap, by calling getNormalizedWeights and setting the token weights to the values returned.

In the contract itself, weights are dynamically computed as needed, based on the block. If the current block is past the end of the last weight change, it just returns the end weights.

So I believe all that's happening here is the last swap was performed when the weights were 0.02/0.98, so that was the last thing the subgraph recorded. If you call the contract, you're going to get the pure end weights, since it's "past the end".

One thing we could do in the subgraph is also update the token weights in handleGradualWeightUpdateScheduled(), since the contract sets the start weights to the current weights. This would be more accurate in cases where the owner adjusts the weight update during the sale, and there were no swaps for a while.

**Comment by nlordell** [comment]
> The weights are stored in a compressed format, so that the entire pool state fits into one slot. That compression and decompression is why they are not exactly 1.0.

Makes sense.

> So I believe all that's happening here is the last swap was performed when the weights were 0.02/0.98, so that was the last thing the subgraph recorded. If you call the contract, you're going to get the pure end weights, since it's "past the end".

Ah OK, so weights only get updated on contract events (specifically `Swaps`) meaning that it can go stale for LBPs.

> One thing we could do in the subgraph is also update the token weights in handleGradualWeightUpdateScheduled()

I think the Graph also lets you setup block handlers, but it may be overkill here.

---

Thanks, this clears everything up! To be perfectly honest, this wasn't really an issue for us (since we are querying weights anyway) - I just ran into this inconsistency when I was verifying the pools I had indexed/queried vs. what was in the subgraph. I was just looking to understand why it was happening. With that in mind, feel free to close this issue.

**Comment by EndymionJkb** [comment]
Yes, a block handler would really bog things down. When swaps stop on an LBP it usually means the sale is over, so it really shouldn't matter in a practical sense. Like the UI and SOR, anything that relies on accurate weights has to call the contract; the subgraph is more for populating historical tables and graphs
